### ISSUE TITLE
How to run: Example Use ??

### ISSUE THREAD

**Issue by mtbagatur** [lilianmallardeau/Multi-object-tracker#1]
Hi @lilianmallardeau,

Can you share the example usage of the code? Thank you..

**Comment by lilianmallardeau** [comment]
Hi,
When I'll have some time, I'll write a decent Readme. I also plan to rewrite the CLI using click instead of argparse, restructure the code a bit, add more object detectors, etc.

In the meantime you can use the builtin argparse help:
```
./main.py --help
```

**Comment by yayuniversal** [comment]
Hi,
When I'll have some time, I'll write a decent Readme. I also plan to rewrite the CLI using click instead of argparse, restructure the code a bit, add more object detectors, etc.

In the meantime you can use the builtin argparse help:
```
./main.py --help
```
